/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/layouts/**/*.{js,ts,jsx,tsx,mdx}',
    './src/utils/**/*.{js,ts,jsx,tsx,mdx}',
    './src/hooks/**/*.{js,ts,jsx,tsx,mdx}',
    './src/stores/**/*.{js,ts,jsx,tsx,mdx}',
    './src/contexts/**/*.{js,ts,jsx,tsx,mdx}',
    './src/router/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        black: '#170B30',
        light: '#F6F6F6',
        'light-2': '#ECEFF1',
        transparent: 'transparent',
        primary: '#5F4DEE',
        'primary-2': '#9941ED',
        'primary-3': '#6258B3',
        'primary-4': '#8251B2',
        'primary-5': '#C64FFF',
        'primary-hover': '#AD67F1',
        secondary: '#FFF438',
        'secondary-2': '#FFF76A',
        gray: '#607D8B',
        'gray-2': '#B0BEC5',
        'gray-3': '#616161',
        'gray-4': '#546E7A',
        'gray-5': '#78909C',
        valid: '#4CB74C',
        'valid-2': '#8DCB8D',
        danger: '#A61212',
        'danger-2': '#A61212',
        'danger-3': '#B84141',
        'danger-4': '#FF2C1D',
        'danger-5': '#650D0D',
      },
      fontFamily: {
        franklin: 'Libre Franklin',
        nunito: 'Nunito',
      },
      boxShadow: {
        '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
        '4xl': '0 50px 100px -20px rgba(0, 0, 0, 0.25)',
      },
    },
  },
  plugins: [],
}
